[build-system]
requires = ["setuptools>=74.1.0", "wheel", "setuptools_scm[toml]>=8.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "pyquadp"
description = "Python's bindings for gcc's libquadmath"

authors = [
    {name="Robert Farmer", email="robert.j.farmer37@gmail.com"}
]

dependencies =[
    "numpy",
    "scipy"
]

readme = "README.md"
requires-python = ">=3.9"
license = "GPL-2.0-or-later"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Code Generators",
]

dynamic = ["version"]


[project.urls]
Homepage = "https://github.com/rjfarmer/pyquadp"

[project.optional-dependencies]
test = ['pytest','pytest-xdist','hypothesis']
coverage = ['pytest', 'pytest-xdist', 'pytest-cov']
dev = ['pre-commit','black', 'pytest','pytest-xdist']
perfomance = ["pytest", "pytest-codspeed", 'pytest-xdist']


[tool.pytest.ini_options]
addopts = "-s -n auto"
testpaths = ["tests"]

[tool.bandit]
exclude_dirs = ["tests"]

[tool.coverage.run]
source = ["pyQuadp"]
parallel = true
concurrency = ["multiprocessing", "thread"]


[tool.setuptools]
ext-modules = [
    {name='qmathc', sources=["pyquadp/qfloat.c", "pyquadp/qmathc.c"], libraries=['quadmath'],py-limited-api=true, language="C"},
    {name='qcmathc', sources=["pyquadp/qfloat.c", "pyquadp/qcmplx.c", "pyquadp/qcmathc.c"], libraries=['quadmath'],py-limited-api=true, language="C"},
    {name='qfloat', sources=["pyquadp/qfloat.c"], libraries=['quadmath'],py-limited-api=true, language="C"},
    {name='qcmplx', sources=["pyquadp/qfloat.c", "pyquadp/qcmplx.c"], libraries=['quadmath'],py-limited-api=true, language="C"},
    {name='qint', sources=["pyquadp/qint.c"], libraries=['quadmath'],py-limited-api=true, language="C"},
]

[tool.setuptools.package-data]
moduleName = ["*.so","*.dll"]