from collections.abc import Sequence
from typing import Any, TypeAlias, overload

import numpy as np
from numpy.typing import ArrayLike, NDArray

from .qmfloat import qfloat

QFloatLike: TypeAlias = qfloat | float | int | str

qarray: Any
dtype: np.dtype[Any]
dtype_num: int

@overload
def arange(stop: QFloatLike) -> NDArray[Any]: ...
@overload
def arange(
    start: QFloatLike, stop: QFloatLike, step: QFloatLike = ...
) -> NDArray[Any]: ...
def linspace(
    start: QFloatLike, stop: QFloatLike, num: int, endpoint: bool = ...
) -> NDArray[Any]: ...
def empty(size: int) -> NDArray[Any]: ...
def full(size: int, value: QFloatLike) -> NDArray[Any]: ...
def zeros(size: int) -> NDArray[Any]: ...
def ones(size: int) -> NDArray[Any]: ...
def from_list(values: Sequence[QFloatLike]) -> NDArray[Any]: ...
def from_array(values: ArrayLike) -> NDArray[Any]: ...
