from collections.abc import Sequence
from typing import Any, TypeAlias, overload

import numpy as np
from numpy.typing import ArrayLike, NDArray

from .qmfloat import qfloat

QFloatLike: TypeAlias = qfloat | float | int | str
ShapeLike: TypeAlias = int | tuple[int, ...]

qarray: Any
dtype: np.dtype[Any]
dtype_num: int

@overload
def arange(stop: QFloatLike) -> NDArray[Any]: ...
@overload
def arange(
    start: QFloatLike, stop: QFloatLike, step: QFloatLike = ...
) -> NDArray[Any]: ...
def linspace(
    start: QFloatLike, stop: QFloatLike, num: int, endpoint: bool = ...
) -> NDArray[Any]: ...
def empty(shape: ShapeLike) -> NDArray[Any]: ...
def full(shape: ShapeLike, value: QFloatLike) -> NDArray[Any]: ...
def zeros(shape: ShapeLike) -> NDArray[Any]: ...
def ones(shape: ShapeLike) -> NDArray[Any]: ...
def from_list(values: Sequence[QFloatLike]) -> NDArray[Any]: ...
def from_array(values: ArrayLike) -> NDArray[Any]: ...
def asarray(
    values: ArrayLike,
    *,
    copy: bool = ...,
    order: str | None = ...,
    ndmin: int = ...,
) -> NDArray[Any]: ...
def array(
    values: ArrayLike,
    *,
    copy: bool = ...,
    order: str | None = ...,
    ndmin: int = ...,
) -> NDArray[Any]: ...
def asfortranarray(values: ArrayLike) -> NDArray[Any]: ...
def ravel(values: ArrayLike, order: str | None = ...) -> NDArray[Any]: ...
def empty_like(values: ArrayLike) -> NDArray[Any]: ...
def zeros_like(values: ArrayLike) -> NDArray[Any]: ...
def ones_like(values: ArrayLike) -> NDArray[Any]: ...
def full_like(values: ArrayLike, value: QFloatLike) -> NDArray[Any]: ...
