from collections.abc import Sequence
from typing import Any, TypeAlias

import numpy as np
from numpy.typing import ArrayLike, NDArray

from .qmcmplx import qcmplx

QComplexLike: TypeAlias = qcmplx | complex
ShapeLike: TypeAlias = int | tuple[int, ...]

qcarray: Any
dtype: np.dtype[Any]
dtype_num: int

def linspace(
    _start: QComplexLike, _stop: QComplexLike, _num: int, _endpoint: bool = ...
) -> NDArray[Any]: ...
def empty(_shape: ShapeLike) -> NDArray[Any]: ...
def full(_shape: ShapeLike, _value: QComplexLike) -> NDArray[Any]: ...
def zeros(_shape: ShapeLike) -> NDArray[Any]: ...
def ones(_shape: ShapeLike) -> NDArray[Any]: ...
def from_list(_values: Sequence[QComplexLike]) -> NDArray[Any]: ...
def from_array(_values: ArrayLike) -> NDArray[Any]: ...
def asarray(
    _values: ArrayLike,
    *,
    copy: bool = ...,
    order: str | None = ...,
    ndmin: int = ...,
) -> NDArray[Any]: ...
def array(
    _values: ArrayLike,
    *,
    copy: bool = ...,
    order: str | None = ...,
    ndmin: int = ...,
) -> NDArray[Any]: ...
def asfortranarray(_values: ArrayLike) -> NDArray[Any]: ...
def ravel(_values: ArrayLike, order: str | None = ...) -> NDArray[Any]: ...
def empty_like(_values: ArrayLike) -> NDArray[Any]: ...
def zeros_like(_values: ArrayLike) -> NDArray[Any]: ...
def ones_like(_values: ArrayLike) -> NDArray[Any]: ...
def full_like(_values: ArrayLike, _value: QComplexLike) -> NDArray[Any]: ...
