from collections.abc import Sequence
from typing import Any, TypeAlias

import numpy as np
from numpy.typing import ArrayLike, NDArray

from .qmcmplx import qcmplx

QComplexLike: TypeAlias = qcmplx | complex

qcarray: Any
dtype: np.dtype[Any]
dtype_num: int

def linspace(
    _start: QComplexLike, _stop: QComplexLike, _num: int, _endpoint: bool = ...
) -> NDArray[Any]: ...
def empty(_size: int) -> NDArray[Any]: ...
def full(_size: int, _value: QComplexLike) -> NDArray[Any]: ...
def zeros(_size: int) -> NDArray[Any]: ...
def ones(_size: int) -> NDArray[Any]: ...
def from_list(_values: Sequence[QComplexLike]) -> NDArray[Any]: ...
def from_array(_values: ArrayLike) -> NDArray[Any]: ...
