from typing import TypeAlias

from .constant import *
from .qmcmplx import qcmplx
from .qmfloat import qfloat

QFloatLike: TypeAlias = qfloat | float | int | str
QComplexLike: TypeAlias = qcmplx | complex

def cabsq(x: QComplexLike) -> qfloat: ...
def cargq(x: QComplexLike) -> qfloat: ...
def cimagq(x: QComplexLike) -> qfloat: ...
def crealq(x: QComplexLike) -> qfloat: ...
def cacoshq(x: QComplexLike) -> qcmplx: ...
def cacosq(x: QComplexLike) -> qcmplx: ...
def casinhq(x: QComplexLike) -> qcmplx: ...
def casinq(x: QComplexLike) -> qcmplx: ...
def catanhq(x: QComplexLike) -> qcmplx: ...
def catanq(x: QComplexLike) -> qcmplx: ...
def ccosq(x: QComplexLike) -> qcmplx: ...
def ccoshq(x: QComplexLike) -> qcmplx: ...
def cexpq(x: QComplexLike) -> qcmplx: ...
def cexpiq(x: QFloatLike) -> qcmplx: ...
def clogq(x: QComplexLike) -> qcmplx: ...
def clog10q(x: QComplexLike) -> qcmplx: ...
def conjq(x: QComplexLike) -> qcmplx: ...
def cpowq(x: QComplexLike, y: QComplexLike | QFloatLike) -> qcmplx: ...
def cprojq(x: QComplexLike) -> qcmplx: ...
def csinq(x: QComplexLike) -> qcmplx: ...
def csinhq(x: QComplexLike) -> qcmplx: ...
def csqrtq(x: QComplexLike) -> qcmplx: ...
def ctanq(x: QComplexLike) -> qcmplx: ...
def ctanhq(x: QComplexLike) -> qcmplx: ...
def phase(x: QComplexLike) -> qfloat: ...
def polar(x: QComplexLike) -> tuple[qfloat, qfloat]: ...
def rect(r: QFloatLike, phi: QFloatLike) -> qcmplx: ...
def acos(x: QComplexLike) -> qcmplx: ...
def acosh(x: QComplexLike) -> qcmplx: ...
def asin(x: QComplexLike) -> qcmplx: ...
def asinh(x: QComplexLike) -> qcmplx: ...
def atan(x: QComplexLike) -> qcmplx: ...
def atanh(x: QComplexLike) -> qcmplx: ...
def cosh(x: QComplexLike) -> qcmplx: ...
def cos(x: QComplexLike) -> qcmplx: ...
def exp(x: QComplexLike) -> qcmplx: ...
def log(x: QComplexLike, base: QComplexLike | QFloatLike | None = ...) -> qcmplx: ...
def log10(x: QComplexLike) -> qcmplx: ...
def pow(x: QComplexLike, y: QComplexLike | QFloatLike) -> qcmplx: ...
def sinh(x: QComplexLike) -> qcmplx: ...
def sin(x: QComplexLike) -> qcmplx: ...
def sqrt(x: QComplexLike) -> qcmplx: ...
def tan(x: QComplexLike) -> qcmplx: ...
def tanh(x: QComplexLike) -> qcmplx: ...
def isfinite(x: QComplexLike) -> bool: ...
def isnan(x: QComplexLike) -> bool: ...
def isinf(x: QComplexLike) -> bool: ...
def isclose(
    a: QComplexLike, b: QComplexLike, *, rel_tol: float = ..., abs_tol: float = ...
) -> bool: ...
