from collections.abc import Sequence
from typing import Any, TypeAlias, overload

import numpy as np
from numpy.typing import ArrayLike, NDArray

from .qmint import qint

QIntLike: TypeAlias = qint | int | str

qiarray: Any
dtype: np.dtype[Any]
dtype_num: int

@overload
def arange(stop: QIntLike) -> NDArray[Any]: ...
@overload
def arange(start: QIntLike, stop: QIntLike, step: QIntLike = ...) -> NDArray[Any]: ...
def empty(_size: int) -> NDArray[Any]: ...
def full(_size: int, _value: QIntLike) -> NDArray[Any]: ...
def zeros(_size: int) -> NDArray[Any]: ...
def ones(_size: int) -> NDArray[Any]: ...
def from_list(_values: Sequence[QIntLike]) -> NDArray[Any]: ...
def from_array(_values: ArrayLike) -> NDArray[Any]: ...
def asarray(_values: ArrayLike) -> NDArray[Any]: ...
def array(_values: ArrayLike) -> NDArray[Any]: ...
def empty_like(_values: ArrayLike) -> NDArray[Any]: ...
def zeros_like(_values: ArrayLike) -> NDArray[Any]: ...
def ones_like(_values: ArrayLike) -> NDArray[Any]: ...
def full_like(_values: ArrayLike, _value: QIntLike) -> NDArray[Any]: ...
