from collections.abc import Sequence
from typing import Any, TypeAlias

from .constant import *
from .qmfloat import qfloat
from .qmint import qint

QFloatLike: TypeAlias = qfloat | float | int | str
QIntLike: TypeAlias = qint | int | str

def acosq(x: QFloatLike) -> qfloat: ...
def acoshq(x: QFloatLike) -> qfloat: ...
def asinq(x: QFloatLike) -> qfloat: ...
def asinhq(x: QFloatLike) -> qfloat: ...
def atanq(x: QFloatLike) -> qfloat: ...
def atanhq(x: QFloatLike) -> qfloat: ...
def atan2q(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def cbrtq(x: QFloatLike) -> qfloat: ...
def ceilq(x: QFloatLike) -> qfloat: ...
def copysignq(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def coshq(x: QFloatLike) -> qfloat: ...
def cosq(x: QFloatLike) -> qfloat: ...
def erfq(x: QFloatLike) -> qfloat: ...
def erfcq(x: QFloatLike) -> qfloat: ...
def exp2q(x: QFloatLike) -> qfloat: ...
def expq(x: QFloatLike) -> qfloat: ...
def expm1q(x: QFloatLike) -> qfloat: ...
def fdimq(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def fabsq(x: QFloatLike) -> qfloat: ...
def finiteq(x: QFloatLike) -> bool: ...
def floorq(x: QFloatLike) -> qfloat: ...
def fmaq(x: QFloatLike, y: QFloatLike, z: QFloatLike) -> qfloat: ...
def fmaxq(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def fminq(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def fmodq(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def frexpq(x: QFloatLike) -> tuple[qfloat, int]: ...
def hypotq(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def ilogbq(x: QFloatLike) -> int: ...
def isinfq(x: QFloatLike) -> bool: ...
def isnanq(x: QFloatLike) -> bool: ...
def issignalingq(x: QFloatLike) -> bool: ...
def j0q(x: QFloatLike) -> qfloat: ...
def j1q(x: QFloatLike) -> qfloat: ...
def jnq(n: QIntLike, x: QFloatLike) -> qfloat: ...
def ldexpq(x: QFloatLike, i: QIntLike) -> qfloat: ...
def lgammaq(x: QFloatLike) -> qfloat: ...
def llrintq(x: QFloatLike) -> int: ...
def llroundq(x: QFloatLike) -> int: ...
def logbq(x: QFloatLike) -> qfloat: ...
def logq(x: QFloatLike) -> qfloat: ...
def log10q(x: QFloatLike) -> qfloat: ...
def log1pq(x: QFloatLike) -> qfloat: ...
def log2q(x: QFloatLike) -> qfloat: ...
def lrintq(x: QFloatLike) -> int: ...
def lroundq(x: QFloatLike) -> int: ...
def modfq(x: QFloatLike) -> tuple[qfloat, qfloat]: ...
def nanq(x: object | None = ...) -> qfloat: ...
def nearbyintq(x: QFloatLike) -> qfloat: ...
def nextafterq(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def powq(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def remainderq(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def remquoq(x: QFloatLike, y: QFloatLike) -> tuple[qfloat, int]: ...
def rintq(x: QFloatLike) -> qfloat: ...
def roundq(x: QFloatLike) -> qfloat: ...
def scalbnq(x: QFloatLike, n: QIntLike) -> qfloat: ...
def scalblnq(x: QFloatLike, n: QIntLike) -> qfloat: ...
def signbitq(x: QFloatLike) -> bool: ...
def sincosq(x: QFloatLike) -> tuple[qfloat, qfloat]: ...
def sinhq(x: QFloatLike) -> qfloat: ...
def sinq(x: QFloatLike) -> qfloat: ...
def sqrtq(x: QFloatLike) -> qfloat: ...
def tanq(x: QFloatLike) -> qfloat: ...
def tanhq(x: QFloatLike) -> qfloat: ...
def tgammaq(x: QFloatLike) -> qfloat: ...
def truncq(x: QFloatLike) -> qfloat: ...
def y0q(x: QFloatLike) -> qfloat: ...
def y1q(x: QFloatLike) -> qfloat: ...
def ynq(n: QIntLike, x: QFloatLike) -> qfloat: ...
def acos(x: QFloatLike) -> qfloat: ...
def acosh(x: QFloatLike) -> qfloat: ...
def asin(x: QFloatLike) -> qfloat: ...
def asinh(x: QFloatLike) -> qfloat: ...
def atan(x: QFloatLike) -> qfloat: ...
def atanh(x: QFloatLike) -> qfloat: ...
def atan2(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def cbrt(x: QFloatLike) -> qfloat: ...
def ceil(x: QFloatLike) -> qfloat: ...
def copysign(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def cosh(x: QFloatLike) -> qfloat: ...
def cos(x: QFloatLike) -> qfloat: ...
def erf(x: QFloatLike) -> qfloat: ...
def erfc(x: QFloatLike) -> qfloat: ...
def exp2(x: QFloatLike) -> qfloat: ...
def exp(x: QFloatLike) -> qfloat: ...
def expm1(x: QFloatLike) -> qfloat: ...
def fabs(x: QFloatLike) -> qfloat: ...
def floor(x: QFloatLike) -> qfloat: ...
def fmax(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def fmin(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def fmod(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def frexp(x: QFloatLike) -> tuple[qfloat, int]: ...
def hypot(*iterable: QFloatLike) -> qfloat: ...
def isinf(x: QFloatLike) -> bool: ...
def isnan(x: QFloatLike) -> bool: ...
def ldexp(x: QFloatLike, y: QIntLike) -> qfloat: ...
def lgamma(x: QFloatLike) -> qfloat: ...
def log(x: QFloatLike, base: QFloatLike | None = ...) -> qfloat: ...
def log10(x: QFloatLike) -> qfloat: ...
def log1p(x: QFloatLike) -> qfloat: ...
def log2(x: QFloatLike) -> qfloat: ...
def modf(x: QFloatLike) -> tuple[qfloat, qfloat]: ...
def nextafter(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def pow(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def remainder(x: QFloatLike, y: QFloatLike) -> qfloat: ...
def sinh(x: QFloatLike) -> qfloat: ...
def sin(x: QFloatLike) -> qfloat: ...
def sqrt(x: QFloatLike) -> qfloat: ...
def tan(x: QFloatLike) -> qfloat: ...
def tanh(x: QFloatLike) -> qfloat: ...
def trunc(x: QFloatLike) -> qfloat: ...
def comb(n: int, k: int) -> int: ...
def factorial(n: int) -> int: ...
def fsum(*iterable: QFloatLike) -> float: ...
def gcd(*integers: int) -> int: ...
def isclose(
    a: QFloatLike, b: QFloatLike, *, rel_tol: float = ..., abs_tol: float = ...
) -> bool: ...
def isfinite(x: QFloatLike) -> bool: ...
def isqrt(n: QIntLike) -> qfloat: ...
def lcm(*integers: int) -> int: ...
def perm(iterable: Any, *, start: int = ...) -> int: ...
def prod(iterable: Any, *, start: int = ...) -> int: ...
def ulp(x: QFloatLike) -> qfloat: ...
def dist(p: Sequence[QFloatLike], q: Sequence[QFloatLike]) -> float: ...
def degrees(x: QFloatLike) -> qfloat: ...
def radians(x: QFloatLike) -> qfloat: ...
