from typing import Any, TypeAlias, overload

from .qmfloat import qfloat

QFloatLike: TypeAlias = qfloat | float | int | str
QComplexLike: TypeAlias = "qcmplx | complex"

class qcmplx:
    _as_parameter_: Any
    real: qfloat
    imag: qfloat

    @overload
    def __new__(cls, _value: QComplexLike | QFloatLike = ...) -> "qcmplx": ...
    @overload
    def __new__(cls, _real: QFloatLike, _imag: QFloatLike) -> "qcmplx": ...
    @classmethod
    def from_bytes(cls, _value: bytes | bytearray | memoryview) -> "qcmplx": ...
    @classmethod
    def from_param(
        cls, _value: QComplexLike | tuple[QFloatLike, QFloatLike]
    ) -> bytes: ...
    def to_bytes(self) -> bytes: ...
    def __getstate__(self) -> dict[str, object]: ...
    def __setstate__(self, _state: dict[str, object]) -> None: ...
    def __bool__(self) -> bool: ...
    def __complex__(self) -> complex: ...
    def conjugate(self) -> "qcmplx": ...
    def __abs__(self) -> qfloat: ...
    def __add__(self, other: QComplexLike | QFloatLike) -> "qcmplx": ...
    def __radd__(self, other: QComplexLike | QFloatLike) -> "qcmplx": ...
    def __sub__(self, other: QComplexLike | QFloatLike) -> "qcmplx": ...
    def __rsub__(self, other: QComplexLike | QFloatLike) -> "qcmplx": ...
    def __mul__(self, other: QComplexLike | QFloatLike) -> "qcmplx": ...
    def __rmul__(self, other: QComplexLike | QFloatLike) -> "qcmplx": ...
    def __truediv__(self, other: QComplexLike | QFloatLike) -> "qcmplx": ...
    def __rtruediv__(self, other: QComplexLike | QFloatLike) -> "qcmplx": ...
    def __pow__(
        self, other: QComplexLike | QFloatLike, modulo: None = ...
    ) -> "qcmplx": ...
    def __neg__(self) -> "qcmplx": ...
    def __pos__(self) -> "qcmplx": ...
