from typing import Any, TypeAlias

QFloatLike: TypeAlias = "qfloat | float | int | str"

class qfloat:
    _as_parameter_: Any

    def __new__(cls, _value: QFloatLike = ...) -> "qfloat": ...
    @classmethod
    def from_bytes(cls, _value: bytes | bytearray | memoryview) -> "qfloat": ...
    @classmethod
    def from_param(cls, _value: QFloatLike) -> bytes: ...
    @classmethod
    def fromhex(cls, _value: str) -> "qfloat": ...
    def to_bytes(self) -> bytes: ...
    def __getstate__(self) -> dict[str, object]: ...
    def __setstate__(self, _state: dict[str, object]) -> None: ...
    def hex(self) -> str: ...
    def as_integer_ratio(self) -> tuple[int, int]: ...
    def __round__(self, ndigits: int | None = ...) -> "qfloat": ...
    def __trunc__(self) -> "qfloat": ...
    def __floor__(self) -> "qfloat": ...
    def __ceil__(self) -> "qfloat": ...
    def is_integer(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __abs__(self) -> "qfloat": ...
    def __add__(self, other: QFloatLike) -> "qfloat": ...
    def __radd__(self, other: QFloatLike) -> "qfloat": ...
    def __sub__(self, other: QFloatLike) -> "qfloat": ...
    def __rsub__(self, other: QFloatLike) -> "qfloat": ...
    def __mul__(self, other: QFloatLike) -> "qfloat": ...
    def __rmul__(self, other: QFloatLike) -> "qfloat": ...
    def __truediv__(self, other: QFloatLike) -> "qfloat": ...
    def __rtruediv__(self, other: QFloatLike) -> "qfloat": ...
    def __floordiv__(self, other: QFloatLike) -> "qfloat": ...
    def __rfloordiv__(self, other: QFloatLike) -> "qfloat": ...
    def __mod__(self, other: QFloatLike) -> "qfloat": ...
    def __rmod__(self, other: QFloatLike) -> "qfloat": ...
    def __pow__(
        self, other: QFloatLike, modulo: QFloatLike | None = ...
    ) -> "qfloat": ...
    def __divmod__(self, other: QFloatLike) -> tuple["qfloat", "qfloat"]: ...
    def __rdivmod__(self, other: QFloatLike) -> tuple["qfloat", "qfloat"]: ...
    def __neg__(self) -> "qfloat": ...
    def __pos__(self) -> "qfloat": ...
