from typing import Any, TypeAlias

QIntLike: TypeAlias = "qint | int | str"

class qint:
    _as_parameter_: Any

    def __new__(cls, _value: QIntLike = ...) -> "qint": ...
    @classmethod
    def from_bytes(cls, _value: bytes | bytearray | memoryview) -> "qint": ...
    @classmethod
    def from_param(cls, _value: QIntLike) -> "qint": ...
    @classmethod
    def fromhex(cls, _value: str) -> "qint": ...
    def to_bytes(self) -> bytes: ...
    def hex(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __abs__(self) -> "qint": ...
    def __add__(self, other: QIntLike) -> "qint": ...
    def __radd__(self, other: QIntLike) -> "qint": ...
    def __sub__(self, other: QIntLike) -> "qint": ...
    def __rsub__(self, other: QIntLike) -> "qint": ...
    def __mul__(self, other: QIntLike) -> "qint": ...
    def __rmul__(self, other: QIntLike) -> "qint": ...
    def __truediv__(self, other: QIntLike) -> float: ...
    def __rtruediv__(self, other: QIntLike) -> float: ...
    def __floordiv__(self, other: QIntLike) -> "qint": ...
    def __rfloordiv__(self, other: QIntLike) -> "qint": ...
    def __mod__(self, other: QIntLike) -> "qint": ...
    def __rmod__(self, other: QIntLike) -> "qint": ...
    def __pow__(self, other: QIntLike, modulo: QIntLike | None = ...) -> "qint": ...
    def __divmod__(self, other: QIntLike) -> tuple["qint", "qint"]: ...
    def __rdivmod__(self, other: QIntLike) -> tuple["qint", "qint"]: ...
    def __and__(self, other: QIntLike) -> "qint": ...
    def __rand__(self, other: QIntLike) -> "qint": ...
    def __or__(self, other: QIntLike) -> "qint": ...
    def __ror__(self, other: QIntLike) -> "qint": ...
    def __xor__(self, other: QIntLike) -> "qint": ...
    def __rxor__(self, other: QIntLike) -> "qint": ...
    def __lshift__(self, other: int) -> "qint": ...
    def __rlshift__(self, other: int) -> "qint": ...
    def __rshift__(self, other: int) -> "qint": ...
    def __rrshift__(self, other: int) -> "qint": ...
    def __neg__(self) -> "qint": ...
    def __pos__(self) -> "qint": ...
    def __invert__(self) -> "qint": ...
