on: ["push", "pull_request"]
name: Coveralls
permissions: {}

jobs:
  coveralls:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - {compiler: gcc, version: 13}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel

      - name: Setup fortran
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
    
      - name: Build
        run: |
            python -m pip install .[coverage] .[test]
        
      - name: Run coveralls
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTEST_COVERAGE: 1
        run: |
          python -m pytest --cov=pyquadp --cov-report lcov:lcov.info

      - name: Upload Coverage Results
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: lcov.info