name: Linux ARM
on: [push, pull_request]
permissions: {}

jobs:
  linux_arm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-24.04-arm]    

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel
          sudo apt-get update
          sudo apt-get install -y gcc gfortran libopenblas-dev libquadmath0-amd64-cross

    
      - name: Build
        run: |
          which gcc
          gcc -E -Wp,-v -xc /dev/null
          python -m pip install .[test]

  
      - name: Test
        run: python -m pytest -v

