on: ["push", "pull_request"]
name: Linux ARM
permissions: {}

jobs:
  LinuxArm:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - {compiler: gcc, version: 13}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel

      - name: Setup fortran
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
    
      - name: Build
        run: python -m pip install .[test]

      - name: Test
        run: python -m pytest -v