name:  PyPy
on: [push, pull_request]
permissions: {}

jobs:
  pypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - {compiler: gcc, version: 12}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up PyPy
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pypy3 -m pip install --upgrade pip
          pypy3 -m pip install build wheel
          sudo apt-get install -y libopenblas-dev

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
    
      - name: Build
        run: pypy3 -m pip install .[test]

      - name: Test
        run: pypy3 -m pytest
